Repository magiclabs/make-magic-app, pull requests merged in 2021-02, with the labels that each got.

#10 Fix NPM tarball omitting dist
  package.json
Labels: patch

#11 Remove 'pkg-up' dependency
  compiled/pkg-up/LICENSE
  compiled/pkg-up/index.js
  compiled/pkg-up/package.json
  lib/config.ts
  package.json
  yarn.lock
Labels: patch

#12 Add option to change which branch templates are sourced from
  lib/cli.ts
  lib/create-app.tsx
  lib/help-text.ts
Labels: patch

#13 Add basic hello world template
  lib/create-app.tsx
  lib/utils/common-prompts.ts
  lib/utils/merge-prompts.ts
  lib/utils/scaffold-helpers.ts
  scaffolds/hello-world/scaffold.tsx
  scaffolds/hello-world/template/example.txt
  scaffolds/hello-world/template/index.html
  scaffolds/hello-world/template/package.json
  scaffolds/hello-world/template/styles.css
  scaffolds/hello-world/template/test.ts
Labels: minor

#14 Add 'react' and 'react-is' dependencies
  package.json
Labels: patch

#16 Use `localhost` as the address for Hello World server
  scaffolds/hello-world/template/package.json
Labels: patch

#17 Document individual template options
  .eslintrc
  compiled/cfonts/index.js
  compiled/decamelize-keys/LICENSE
  compiled/decamelize-keys/index.js
  compiled/decamelize-keys/package.json
  compiled/meow/index.js
  lib/cli.ts
  lib/help-text.ts
  lib/utils/common-prompts.ts
  lib/utils/scaffold-helpers.ts
  package.json
  scaffolds/hello-world/scaffold.tsx
Labels: minor, skip-release

#18 Add "Hello world (React)" template
  lib/help-text.ts
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-react/template/package.json
  scaffolds/hello-world-react/template/src/components/App.js
  scaffolds/hello-world-react/template/src/components/Callback.js
  scaffolds/hello-world-react/template/src/components/Login.js
  scaffolds/hello-world-react/template/src/components/Profile.js
  scaffolds/hello-world-react/template/src/index.html
  scaffolds/hello-world-react/template/src/index.js
  scaffolds/hello-world-react/template/src/magic.js
  scaffolds/hello-world-react/template/src/styles.css
Labels: minor

#19 Small template updates
  bin.js
  cli/config.ts
  cli/create-app.tsx
  cli/help-text.ts
  cli/index.ts
  cli/types/shims.d.ts
  cli/utils/common-prompts.ts
  cli/utils/filter-nil-values.ts
  cli/utils/make-dir.ts
  cli/utils/merge-prompts.ts
  cli/utils/path-helpers.ts
  cli/utils/repo.ts
  cli/utils/scaffold-helpers.ts
  lib/help-text.ts
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-react/template/src/components/App.js
  scaffolds/hello-world-react/template/src/components/Callback.js
  scaffolds/hello-world-react/template/src/components/Loading.js
  scaffolds/hello-world-react/template/src/components/Login.js
  scaffolds/hello-world-react/template/src/components/Profile.js
  scaffolds/hello-world-react/template/src/index.html
  scaffolds/hello-world-react/template/src/index.js
  scaffolds/hello-world/scaffold.tsx
  scaffolds/hello-world/template/index.html
  tsconfig.json
Labels: patch

#20 Added Binance Smart Chain scaffold
  scaffolds/binance-smart-chain/scaffold.tsx
  scaffolds/binance-smart-chain/template/index.html
  scaffolds/binance-smart-chain/template/package.json
  scaffolds/binance-smart-chain/template/styles.css
Labels: minor, skip-release

#21 Included gas to allow contract deploy
  scaffolds/binance-smart-chain/template/index.html
Labels: patch, skip-release

#23 Fix broken template interpolation in `hello-world-social-logins`
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-social-login/scaffold.tsx
  scaffolds/hello-world-social-login/template/src/magic.js
  scaffolds/hello-world/scaffold.tsx
Labels: patch

#24 Add validation for template data provided as CLI flags
  .eslintrc
  cli/create-app.tsx
  cli/help-text.ts
  cli/index.ts
  cli/types/utility-types.ts
  cli/utils/common-prompts.ts
  cli/utils/errors-warnings.ts
  cli/utils/scaffold-helpers.ts
  compiled/decamelize/LICENSE
  compiled/decamelize/index.js
  compiled/decamelize/package.json
  package.json
  scaffolds/binance-smart-chain/scaffold.tsx
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-social-login/scaffold.tsx
  scaffolds/hello-world/scaffold.tsx
  scaffolds/prompts.ts
  tsconfig.json
  yarn.lock
Labels: minor

#25 Add `--help` call-to-action upon reaching any validation message
  cli/create-app.tsx
  cli/index.ts
  cli/utils/scaffold-helpers.ts
  scaffolds/prompts.ts
Labels: internal, patch

#26 Update NCC dependencies
  compiled/cfonts/index.js
  compiled/decamelize-keys/index.js
  compiled/meow/index.js
Labels: dependencies, internal, patch

#27 Use exit code 0 upon --help or --version
  cli/index.ts
  scaffolds/prompts.ts
Labels: patch

#28 Fix 'decamelize' usage
  cli/create-app.tsx
Labels: internal, patch

#29 Remove 'meow' dependency, parse flags with 'yargs-parser'
  cli/create-app.tsx
  cli/flags.ts
  cli/help-text.ts
  cli/index.ts
  cli/utils/scaffold-helpers.ts
  compiled/cfonts/index.js
  compiled/got/index.js
  compiled/meow/LICENSE
  compiled/meow/index.js
  compiled/meow/package.json
  compiled/yargs-parser/LICENSE
  compiled/yargs-parser/index.js
  compiled/yargs-parser/package.json
  package.json
  scaffolds/prompts.ts
  scripts/ncc:add.ts
  tsconfig.json
  yarn.lock
Labels: internal, patch

#30 Change '--public-api-key' to '--publishable-api-key'
  scaffolds/binance-smart-chain/scaffold.tsx
  scaffolds/binance-smart-chain/template/index.html
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-react/template/src/magic.js
  scaffolds/hello-world-social-login/scaffold.tsx
  scaffolds/hello-world-social-login/template/src/magic.js
  scaffolds/hello-world/scaffold.tsx
  scaffolds/hello-world/template/index.html
  scaffolds/prompts.ts
Labels: major

#31 Updated BSC nomenclature with link to testnet faucet
  scaffolds/binance-smart-chain/template/index.html
  scaffolds/binance-smart-chain/template/styles.css
Labels: patch

#32 Add 'zombi', 'react', and 'react-is' as NCC dependencies
  cli/create-app.tsx
  cli/index.ts
  cli/utils/merge-prompts.ts
  compiled/cfonts/index.js
  compiled/react-is/LICENSE
  compiled/react-is/index.js
  compiled/react-is/package.json
  compiled/react/LICENSE
  compiled/react/index.js
  compiled/react/package.json
  compiled/zombi/LICENSE
  compiled/zombi/index.js
  compiled/zombi/package.json
  package.json
  scaffolds/binance-smart-chain/scaffold.tsx
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-social-login/scaffold.tsx
  scaffolds/hello-world/scaffold.tsx
  scaffolds/prompts.ts
  scripts/minify.ts
  scripts/ncc:add.ts
  tsconfig.json
  yarn.lock
Labels: patch

#34 Update dependencies
  compiled/cfonts/index.js
  compiled/zombi/index.js
  compiled/zombi/package.json
  package.json
  yarn.lock
Labels: dependencies, patch

#35 added nextjs, hasura templates. updated react template to include env…
  scaffolds/binance-smart-chain/scaffold.tsx
  scaffolds/hasura/scaffold.tsx
  scaffolds/hasura/template/.env.local
  scaffolds/hasura/template/README.md
  scaffolds/hasura/template/components/loading.js
  scaffolds/hasura/template/magic.js
  scaffolds/hasura/template/package.json
  scaffolds/hasura/template/pages/_app.js
  scaffolds/hasura/template/pages/api/login.js
  scaffolds/hasura/template/pages/callback.js
  scaffolds/hasura/template/pages/index.js
  scaffolds/hasura/template/pages/login.js
  scaffolds/hasura/template/public/favicon.ico
  scaffolds/hasura/template/style.css
  scaffolds/hello-world-react/template/.env
  scaffolds/hello-world-react/template/src/magic.js
  scaffolds/next/scaffold.tsx
  scaffolds/next/template/.env.local
  scaffolds/next/template/components/loading.js
  scaffolds/next/template/magic.js
  scaffolds/next/template/package.json
  scaffolds/next/template/pages/_app.js
  scaffolds/next/template/pages/api/login.js
  scaffolds/next/template/pages/callback.js
  scaffolds/next/template/pages/index.js
  scaffolds/next/template/pages/login.js
  scaffolds/next/template/public/favicon.ico
  scaffolds/next/template/style.css
  scaffolds/prompts.ts
Labels: minor, skip-release

#36 Add Twitter OAuth to Social Logins scaffold
  .eslintignore
  .eslintrc
  .eslintrc.js
  .husky/.gitignore
  .husky/pre-commit
  .lintstagedrc.json
  package.json
  scaffolds/binance-smart-chain/scaffold.tsx
  scaffolds/hasura/scaffold.tsx
  scaffolds/hello-world-react/scaffold.tsx
  scaffolds/hello-world-social-login/scaffold.tsx
  scaffolds/hello-world-social-login/template/src/social-logins/twitter.js
  scaffolds/hello-world/scaffold.tsx
  scaffolds/next/scaffold.tsx
  scaffolds/prompts.ts
  yarn.lock
Labels: minor
