Repository magiclabs/make-magic-app, pull requests merged in 2024-01, with the labels that each got.

#121 Removed deprecated package. Updated magic-sdk package to latest version
  scaffolds/nextjs-dedicated-wallet/scaffold.tsx
  scaffolds/nextjs-dedicated-wallet/template/package.json
  scaffolds/nextjs-dedicated-wallet/template/src/components/magic/MagicProvider.tsx
  scaffolds/nextjs-dedicated-wallet/template/src/components/magic/auth/EmailOTP.tsx
  scaffolds/nextjs-dedicated-wallet/template/src/components/magic/auth/SMSOTP.tsx
  scaffolds/nextjs-dedicated-wallet/template/src/components/magic/cards/WalletMethodsCard.tsx
  scaffolds/nextjs-dedicated-wallet/template/src/components/magic/wallet-methods/UpdatePhone.tsx
  scaffolds/nextjs-dedicated-wallet/template/src/styles/globals.css
  scaffolds/nextjs-flow-dedicated-wallet/scaffold.tsx
  scaffolds/nextjs-flow-dedicated-wallet/template/package.json
  scaffolds/nextjs-flow-dedicated-wallet/template/src/components/magic/MagicProvider.tsx
  scaffolds/nextjs-flow-dedicated-wallet/template/src/components/magic/auth/EmailOTP.tsx
  scaffolds/nextjs-flow-dedicated-wallet/template/src/components/magic/auth/SMSOTP.tsx
  scaffolds/nextjs-flow-dedicated-wallet/template/src/components/magic/cards/WalletMethodsCard.tsx
  scaffolds/nextjs-flow-dedicated-wallet/template/src/components/magic/wallet-methods/UpdatePhone.tsx
  scaffolds/nextjs-flow-dedicated-wallet/template/src/styles/globals.css
  scaffolds/nextjs-flow-universal-wallet/template/src/components/magic/Home.tsx
  scaffolds/nextjs-flow-universal-wallet/template/src/components/magic/Login.tsx
  scaffolds/nextjs-flow-universal-wallet/template/src/styles/globals.css
  scaffolds/nextjs-solana-dedicated-wallet/scaffold.tsx
  scaffolds/nextjs-solana-dedicated-wallet/template/package.json
  scaffolds/nextjs-solana-dedicated-wallet/template/src/components/magic/MagicProvider.tsx
  scaffolds/nextjs-solana-dedicated-wallet/template/src/components/magic/auth/EmailOTP.tsx
  scaffolds/nextjs-solana-dedicated-wallet/template/src/components/magic/auth/SMSOTP.tsx
  scaffolds/nextjs-solana-dedicated-wallet/template/src/components/magic/cards/WalletMethodsCard.tsx
  scaffolds/nextjs-solana-dedicated-wallet/template/src/components/magic/wallet-methods/UpdatePhone.tsx
  scaffolds/nextjs-solana-dedicated-wallet/template/src/styles/globals.css
  scaffolds/nextjs-universal-wallet/template/src/components/magic/Home.tsx
  scaffolds/nextjs-universal-wallet/template/src/styles/globals.css
Labels: minor

#120 Feat/132 injecting ejs data
  .gitignore
  package.json
  scaffolds/dev-data.ts
  scaffolds/nextjs-dedicated-wallet/scaffold.ts
  scaffolds/nextjs-dedicated-wallet/template/package-lock.json
  scaffolds/nextjs-flow-dedicated-wallet/scaffold.ts
  scaffolds/nextjs-flow-universal-wallet/scaffold.ts
  scaffolds/nextjs-solana-dedicated-wallet/scaffold.ts
  scaffolds/nextjs-universal-wallet/scaffold.ts
  scripts/template_dev/ejs_dev_script.js
  scripts/template_dev/utils.js
  yarn.lock
Labels: minor, skip-release

#124 Feat/81 contribution guide
  CONTRIBUTING.md
Labels: skip-release
